#version: '3'
name: go-laravel-templ

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:17.2'
    container_name: postgres-templ
    ports:
      - "5432:5432"
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rapidus
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:7.4-alpine'
    container_name: redis-templ
    ports:
      - "6379:6379"
    restart: no
    volumes:
      - ./db-data/redis/:/data

  #  start MariaDB, and ensure that data is stored to a mounted volume
  mariadb:
    image: 'mariadb:11.7'
    container_name: mariadb-templ
    ports:
      - "3306:3306"
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rapidus
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password

    volumes:
      - ./db-data/mariadb:/var/lib/mysql
